#!/bin/bash

# Invoke this script, pass in exercise number as an argument
# Run on successful lint
# Usage Example
# >>> sh run 15

# ./cpplint.py $1/main.cpp

if [ -e $1/stdin ]; then
    cat $1/stdin | python3 $1/main.py
else
    python3 $1/main.py
fi

