#!/bin/bash

# Invoke this script, pass in exercise number as an argument
# Usage Example
# >>> sh run 15

g++ -std=c++14 -o tmp.out $1/main.cpp
if [ -e $1/stdin ]; then
    cat $1/stdin | ./tmp.out
else
    ./tmp.out
fi
rm tmp.out

